# SERVER
server.port=8081

# APPLICATION
spring.application.name=guidance-app

# DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/playground
spring.datasource.username=postgres
spring.datasource.password=Ph@ssain2025
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# LOGGING
logging.level.root=INFO
logging.level.com.parvez.guidance=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE